export const agentTemplates = [
  {
    templateID: 'planner',
    name: 'Planner Agent',
    avatarURL: 'https://api.dicebear.com/7.x/bottts/svg?seed=planner',
    provider: 'openai',
    defaultEndpoint: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o-mini',
    defaultSystemPrompt: 'You are a planning agent. Break user goals into clear, verifiable steps.',
    defaultToolIDs: ['get_current_time', 'read_conversation_messages', 'delegate_to_agent'],
    defaultRuntime: 'openai-tools',
    defaultWorkerTemplateID: 'coder',
    description: 'Breaks goals into plans and coordinates follow-up work.',
    tags: ['planning', 'workflow'],
    status: 'active',
  },
  {
    templateID: 'coder',
    name: 'Coder Agent',
    avatarURL: 'https://api.dicebear.com/7.x/bottts/svg?seed=coder',
    provider: 'openai',
    defaultEndpoint: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o-mini',
    defaultSystemPrompt: 'You are a coding agent. Prefer small, tested changes and explain tradeoffs clearly.',
    defaultToolIDs: ['get_current_time', 'read_conversation_messages', 'workspace_read', 'workspace_write', 'bash', 'local_agent_run'],
    defaultRuntime: 'openai-tools',
    defaultWorkerTemplateID: '',
    description: 'Helps with code analysis, implementation planning, and controlled edits.',
    tags: ['coding', 'review'],
    status: 'active',
  },
  {
    templateID: 'chatgpt',
    name: 'ChatGPT',
    avatarURL: 'https://api.dicebear.com/7.x/bottts/svg?seed=chatgpt',
    provider: 'openai',
    defaultEndpoint: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o-mini',
    defaultSystemPrompt: 'You are a helpful assistant. Be concise and accurate.',
    defaultToolIDs: ['get_current_time'],
    defaultRuntime: 'openai-tools',
    defaultWorkerTemplateID: '',
    description: 'General-purpose conversational assistant.',
    tags: ['general'],
    status: 'active',
  },
  {
    templateID: 'reviewer',
    name: 'Reviewer Agent',
    avatarURL: 'https://api.dicebear.com/7.x/bottts/svg?seed=reviewer',
    provider: 'openai',
    defaultEndpoint: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o-mini',
    defaultSystemPrompt: 'You are a code review agent. Review implementation quality, edge cases, maintainability, and risks. Return concise actionable feedback.',
    defaultToolIDs: ['get_current_time', 'read_conversation_messages', 'workspace_read', 'bash'],
    defaultRuntime: 'openai-tools',
    defaultWorkerTemplateID: '',
    description: 'Reviews code for correctness, edge cases, and maintainability.',
    tags: ['review', 'quality'],
    status: 'active',
  },
  {
    templateID: 'claude-code',
    name: 'Claude Code',
    avatarURL: 'https://api.dicebear.com/7.x/bottts/svg?seed=claude-code',
    provider: 'local-cli',
    defaultEndpoint: '',
    defaultModel: 'claude',
    defaultSystemPrompt: 'You are Claude Code running locally. Execute the user coding task inside the sandbox only, then report files changed, command output, and verification results.',
    defaultToolIDs: ['get_current_time', 'read_conversation_messages', 'workspace_read', 'workspace_write', 'bash', 'local_agent_run'],
    defaultRuntime: 'local-cli-agent',
    defaultLocalAgentProvider: 'claude',
    defaultWorkerTemplateID: '',
    description: 'Runs the locally configured Claude Code CLI in an isolated sandbox; changes require patch approval before reaching the repo.',
    tags: ['coding', 'local-cli', 'anthropic'],
    status: 'active',
  },
  {
    templateID: 'codex-cli',
    name: 'Codex CLI',
    avatarURL: 'https://api.dicebear.com/7.x/bottts/svg?seed=codex-cli',
    provider: 'local-cli',
    defaultEndpoint: '',
    defaultModel: 'codex',
    defaultSystemPrompt: 'You are Codex CLI running locally. Execute the user coding task inside the sandbox only, then report files changed, command output, and verification results.',
    defaultToolIDs: ['get_current_time', 'read_conversation_messages', 'workspace_read', 'workspace_write', 'bash', 'local_agent_run'],
    defaultRuntime: 'local-cli-agent',
    defaultLocalAgentProvider: 'codex',
    defaultWorkerTemplateID: '',
    description: 'Runs the locally configured Codex CLI in an isolated sandbox; changes require patch approval before reaching the repo.',
    tags: ['coding', 'local-cli', 'codex'],
    status: 'active',
  },
  {
    templateID: 'opencode-cli',
    name: 'OpenCode',
    avatarURL: 'https://api.dicebear.com/7.x/bottts/svg?seed=opencode-cli',
    provider: 'local-cli',
    defaultEndpoint: '',
    defaultModel: 'opencode',
    defaultSystemPrompt: 'You are OpenCode running locally. Execute the user coding task inside the sandbox only, then report files changed, command output, and verification results.',
    defaultToolIDs: ['get_current_time', 'read_conversation_messages', 'workspace_read', 'workspace_write', 'bash', 'local_agent_run'],
    defaultRuntime: 'local-cli-agent',
    defaultLocalAgentProvider: 'opencode',
    defaultWorkerTemplateID: '',
    description: 'Runs the locally configured OpenCode CLI in an isolated sandbox; changes require patch approval before reaching the repo.',
    tags: ['coding', 'local-cli', 'opencode'],
    status: 'active',
  },
];

export function listActiveTemplates() {
  return agentTemplates.filter((template) => template.status === 'active');
}

export function getTemplate(templateID) {
  return listActiveTemplates().find((template) => template.templateID === templateID);
}
